language: python
python:
- 3.3
- 3.4

before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
# The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm

install:
- conda install --yes -c https://conda.binstar.org/openhydrology python=$TRAVIS_PYTHON_VERSION pip nose appdirs=1.4 Jinja2=2.7 floodestimation=0.3.0
- python setup.py install
 
script:
- nosetests
